name: C/C++ CI and Docker Multiarch Build

on:
  push:
    branches: [ "branchHTTPservMulti" ]
  pull_request:
    branches: [ "branchHTTPservMulti" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y autoconf automake g++ libboost-test-dev

      - name: QEMU install
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build Dockerfile image for amd64
        run: docker buildx build --platform linux/amd64 -t markshukyhin/httpserver:amd64 --push .

      - name: Build Dockerfile image for arm64
        run: docker buildx build --platform linux/arm64 -t markshukyhin/httpserver:arm64 --push .

      - name: Create manifest
        run: |
          docker manifest create markshukyhin/httpserver:latest \
            --amend markshukyhin/httpserver:amd64 \
            --amend markshukyhin/httpserver:arm64

      - name: Push manifest to Docker Hub
        run: docker manifest push markshukyhin/httpserver:latest
