name: C/C++ CI

on:
  push:
    branches: [ "branchHTTPservMulti" ]
  pull_request:
    branches: [ "branchHTTPservMulti" ]
  workflow_dispatch:
    branches: [ "branchHTTPservMulti" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: build ls
        run: docker buildx ls
        
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build Docker image
        run: |
           docker build -f ./Dockerfile -t markshulyhin/funcaserv .
