name: C/C++ CI

on:
  push:
    branches: [ "branchHTTPServer" ]
  pull_request:
    branches: [ "branchHTTPServer" ]
  workflow_dispatch:
    branches: [ "branchHTTPServer" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: ./configure
        run: ./configure

      - name: make
        run: make

      - name: Run check
        run: make check

      - name: Run distcheck
        run: make distcheck
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ variables.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: markshukyhin/optimadevops:latest
