name: C/C++ CI

on:
  push:
    branches: [ "branchHTTPservMulti" ]
  pull_request:
    branches: [ "branchHTTPservMulti" ]
  workflow_dispatch:
    branches: [ "branchHTTPservMulti" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y autoconf automake g++ libboost-test-dev

      - name: QEMU install
        uses: docker/setup-qemu-action@v3

      - name: Install Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: build ls
        run: docker buildx ls

      - name: Log in to the Container registry
        run: docker login -u ${{ vars.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_TOKEN }}

      - name: Build Dockerfile image for amd64
        run: docker build --platform=linux/amd64 -t markshukyhin/httpserver:amd64 --push .

      - name: Build Dockerfile image for arm64
        run: docker build --platform=linux/arm64 -t markshukyhin/httpserver:arm64 --push .

      - name: Create manifest
        run: docker manifest create markshukyhin/httpserver --amend markshukyhin/httpserver:amd64 --amend markshukyhin/httpserver:arm64

      - name: Push manifest to docker hub
        run: docker manifest push markshukyhin/httpserver
